### ISSUE TITLE
在运行Test_Ours.py脚本时，无法找到model.Restormer模块

### ISSUE THREAD

**Issue by hannahwang0711** [diamondxx/LIE-code#5]
Traceback (most recent call last):
  File "Test_Ours.py", line 9, in <module>
    from model import *
  File "/***/LIE-code-main/model/__init__.py", line 1, in <module>
    from .Restormer import Restormer
ModuleNotFoundError: No module named 'model.Restormer'

**Comment by diamondxx** [comment]
> Traceback (most recent call last): File "Test_Ours.py", line 9, in from model import * File "/***/LIE-code-main/model/**init**.py", line 1, in from .Restormer import Restormer ModuleNotFoundError: No module named 'model.Restormer'

Hi,
Just delete all references to the ‘.Restormer’ package in the ‘init.py’ script.

**Comment by hannahwang0711** [comment]
Hi, something is wrong when i run the test:

Current test scene is: scene0011
Traceback (most recent call last):
  File "Test_Ours.py", line 265, in <module>
    main(config)
  File "Test_Ours.py", line 107, in main
    test_dataset = RealLowlightDataset_test(scene_path)
  File "/home/xxxx/LIE-code-main/dataset/RealLowlightDataset.py", line 101, in __init__
    self.voxels_num = len(os.listdir(self.path_to_voxels_file))
AttributeError: 'RealLowlightDataset_test' object has no attribute 'path_to_voxels_file'

The error is located at:

        self.zx = os.path.join(base_folder, 'voxels')
        self.voxels_num = len(os.listdir(self.path_to_voxels_file))

After I change self.zx to self.path_to_voxels_file, another error comes out.

**Comment by hannahwang0711** [comment]
> > Traceback (most recent call last): File "Test_Ours.py", line 9, in from model import * File "/***/LIE-code-main/model/**init**.py", line 1, in from .Restormer import Restormer ModuleNotFoundError: No module named 'model.Restormer'
> 
> Hi, Just delete all references to the ‘.Restormer’ package in the ‘init.py’ script.

Hi, something is wrong when i run the test:

Current test scene is: scene0011
Traceback (most recent call last):
  File "Test_Ours.py", line 265, in <module>
    main(config)
  File "Test_Ours.py", line 107, in main
    test_dataset = RealLowlightDataset_test(scene_path)
  File "/home/xxxx/LIE-code-main/dataset/RealLowlightDataset.py", line 101, in __init__
    self.voxels_num = len(os.listdir(self.path_to_voxels_file))
AttributeError: 'RealLowlightDataset_test' object has no attribute 'path_to_voxels_file'

The error is located at:

        self.zx = os.path.join(base_folder, 'voxels')
        self.voxels_num = len(os.listdir(self.path_to_voxels_file))

After I change self.zx to self.path_to_voxels_file, another error comes out.
